name: Lint with ruff

on:
  workflow_call:

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run ruff
      run: |
        ruff check .
